language: android

sudo: false
env:
  global:
    - TERM=dumb

android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'

script:
  - which android-update-sdk
  - cat android-update-sdk
  - echo 'hello'
